<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tyuiu.Ahmdi2.Sprint2.Task3.V19.Lib\Tyuiu.Ahmdi2.Sprint2.Task3.V19.Lib.csproj" />
  </ItemGroup>

</Project>
